### ISSUE TITLE
A question about the genome coordinates file when running run_cicero()

### ISSUE THREAD

**Issue by chent5** [cole-trapnell-lab/cicero#10]
Thanks a lot for developing this package. My scATAC-seq data was aligned to GRCh38. In your package, the human hg19 coordinates can be accessed with data("human.hg19.genome"). Where can I find the genome coordinates file for human GRCh38? Thank you so much!

**Comment by hpliner** [comment]
You can find info on where to download this in the FAQs on the website [here](https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#frequently-asked-questions)
