### ISSUE TITLE
hg38?

### ISSUE THREAD

**Issue by wfma** [cole-trapnell-lab/cicero#13]
Hi, is there a human.hg38.genome reference available to run cicero? My previous upstream analysis used the hg38 and I wish to be consistent. (Not sure if it matters tho).

Thanks,
Wei

**Comment by hpliner** [comment]
Hello, you can find instructions on how to get the reference for any genome here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#frequently-asked-questions

Best,
Hannah
