### ISSUE TITLE
cicero across samples

### ISSUE THREAD

**Issue by AnjaliC4** [cole-trapnell-lab/cicero#14]
Hi, thanks for this awesome tool!

I was wondering how can I combine multiple samples before creating a gene activity matrix using cicero? And store the sample info in metadata.

Also if I were to correct for batch effects, should I do that before creating gene activity matrix and cell-type annotation?

Thanks!!
Anjali

**Comment by hpliner** [comment]
Hello,
Check out the monocle3 function [combine_cds](https://cole-trapnell-lab.github.io/monocle3/docs/starting/#combine_cds), I think it should do what you're looking for. 

For batch, the gene activity calculation does not take into account dimensionality reduction, etc, so doing batch correction won't change the outcome.

Best,
Hannah

**Comment by hpliner** [comment]
Going to go ahead and close. Reopen if you have further issues
