### ISSUE TITLE
question: Comparing two Cicero maps

### ISSUE THREAD

**Issue by doublehelixlf** [cole-trapnell-lab/cicero#15]
May I ask a question about the way to compare different Cicero CCAN maps, as described in Pliner et.al., Mol Cell 2018 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6582963/)?

Below is the relevant section in the Methods in the paper:
Different Cicero CCAN maps were matched using the push-relabel algorithm for maximum matching in a weighted bipartite graph (Goldberg and Tarjan, 1986). Specifically, we used the maxmatching package in R to calculate the matching. Maximum matching in weighted bipartite graphs is a one-to-one matching such that the edge weights are maximized. In the case of comparing Cicero CCAN maps, the maximum matching is the one-to-one match of CCANs from map 1 to CCANs from map 2 such that the largest number of peaks is shared across the maps overall.

Is there any code available to do this?
Thanks for the help!

**Comment by hpliner** [comment]
Hello, Looking back at the old analysis scripts, it looks like I used an R function (below) to do the calculations. The two inputs for the function are the outputs of generate_ccans. Hope this helps!

```
find_best_ccan_match <- function(ccans1, ccans2) {
  names(ccans1) <- c("Peak", "CCAN1")
  names(ccans2) <- c("Peak", "CCAN2")
  comps_mem <- merge(ccans1, ccans2, all=TRUE)
  comps_mem$value <- 1
  
  comps_mem$CCAN1 <- paste0("C1_", comps_mem$CCAN1)
  comps_mem$CCAN2 <- paste0("C2_", comps_mem$CCAN2)
  
  comps_mem_temp <- subset(comps_mem, CCAN1 != "C1_NA" | CCAN2 != "C2_NA")
  comps_mem_dc <- reshape2::dcast(CCAN1 ~ CCAN2, value.var = "value", data = comps_mem_temp)
  
  comps_mem_dc <- subset(comps_mem_dc, CCAN1 != "C1_NA")
  comps_mem_dc <- comps_mem_dc[,1:(ncol(comps_mem_dc) - 1)]
  row.names(comps_mem_dc) <- comps_mem_dc$CCAN1
  comps_mem_dc$CCAN1 <- NULL
  
  comps_mem_dc_melt <- comps_mem_dc
  comps_mem_dc_melt$CCAN1 <- row.names(comps_mem_dc_melt)
  comps_mem_dc_melt <- melt(comps_mem_dc_melt, id.vars = "CCAN1")
  names(comps_mem_dc_melt) <- c("from", "to", "weight")
  comps_mem_dc_melt <- subset(comps_mem_dc_melt, from != to)
  grph <- igraph::graph_from_data_frame(subset(comps_mem_dc_melt, weight > 0), directed = FALSE)
  igraph::V(grph)$type <- grepl("orig", igraph::V(grph))
  mbm <- maxmatching::maxmatching(grph)
  
  matching <- data.frame(CCAN1 = mbm$matching, CCAN2 = names(mbm$matching))
  matching <- subset(matching, grepl("C1", CCAN1) & grepl("C2", CCAN2))
  matching$CCAN1 <- gsub("C1_", "", matching$CCAN1)
  matching$CCAN2 <- gsub("C2_", "", matching$CCAN2)
  return(matching)
}
```

**Comment by doublehelixlf** [comment]
Thanks Hannah for the reply. This helps a lot!
