### ISSUE TITLE
Addmetada to  cicero object

### ISSUE THREAD

**Issue by vfriver** [cole-trapnell-lab/cicero#16]
Dear, 
I am trying to add metadata to cicero object but I can not add

Code> 

metadad <- read.csv(
  file = "/metadata.csv",
  header = TRUE,
  row.names = 1
)

cds <- load_mm_data(mat_path = "/matrix.mtx", 
                    feature_anno_path = "/features.tsv", 
                    cell_anno_path = "/barcodes.tsv",
                    cell_metadata = metadad).

The final object does not have the colData with metadata. 

Can you help me please..

**Comment by hpliner** [comment]
Hello, 
The function load_mm_data does not have an argument "cell_metadata". You'll need to load the cds without the metadata and then add to the colData either by merging or using cbind (if the rows are in the right order).
