### ISSUE TITLE
Question: customize the cell group instead of k-nearest-neighbors approach

### ISSUE THREAD

**Issue by yangjim221** [cole-trapnell-lab/cicero#17]
Hello,

I have known the cell type of each cell in my data. So I want to annotate the cell type by myself instead of running cicero_cds <- make_cicero_cds(input_cds, reduced_coordinates = umap_coords).

Can you help me?

Thanks

Jinmin

**Comment by hpliner** [comment]
Hello,

If you know the cell groups you want to use, you can skip the make_cicero_cds function by making an aggregated cell data set (i.e. summing the counts of your groups to make pseudo-cells) and passing that in to the run_cicero steps. I will note that this approach was not used in the original paper and has not been robustly tested. Hope this helps, reopen if you have further questions
Hannah
