### ISSUE TITLE
sparse matrix format

### ISSUE THREAD

**Issue by Leonrunning** [cole-trapnell-lab/cicero#18]
Hi,

Would you please let me know how to prepare the required sparse matrix format? I am working on a Seurat object and am able to convert it to a CDS object for Monocle2.  I created a data matrix as below but make_atac_cds does not recognize it. Thanks Leon

6 x 8026 sparse Matrix of class "dgCMatrix"
  [[ suppressing 54 column names 'AAACAGCCAAGCGATG-4', 'AAACAGCCACTAGCGT-5', 'AAACAGCCATAATCGT-2' ... ]]
                                                                                                                       
chr1-3054393-3054623 . . . . . . . .        . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-3086804-3087243 . . . . . . . .        . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-3100009-3100802 . . . . . . . 3.949646 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-3117783-3118238 . . . . . . . .        . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-3119514-3120621 . . . . . . . .        . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-3121355-3121666 . . . . . . . .        . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
                                           
chr1-3054393-3054623 . . . . . . . . ......
chr1-3086804-3087243 . . . . . . . . ......
chr1-3100009-3100802 . . . . . . . . ......
chr1-3117783-3118238 . . . . . . . . ......
chr1-3119514-3120621 . . . . . . . . ......
chr1-3121355-3121666 . . . . . . . . ......

 .....suppressing 7972 columns in show(); maybe adjust 'options(max.print= *, width = *)'

**Comment by hpliner** [comment]
Hello, make_atac_cds is only necessary if you don't already have a CDS object. If you're able to convert your object to a cds already then you should be able to skip right to the make_cicero_cds step. Reopen if this didn't answer your question
