### ISSUE TITLE
Gene annotation for other chromosomes?

### ISSUE THREAD

**Issue by lzj1769** [cole-trapnell-lab/cicero#2]
Hi,

in the tutorial, the gene annotation of chromosome 18 was provided as an example,
so my question is where I can find the annotation, or how I can generate the annotation for other chromosomes?

Thanks,
Zhijian

**Comment by hpliner** [comment]
Hi Zhijian, 

The entire hg19 genome coordinates are included in the package, it is just subsetted in the tutorial: data("human.hg19.genome")

The coordinates for other genomes/builds are available from UCSC genome browser, for example, mm10 is here: http://hgdownload.soe.ucsc.edu/goldenPath/mm10/database/chromInfo.txt.gz

Hannah
