### ISSUE TITLE
Plot with no axis labels

### ISSUE THREAD

**Issue by JunxiFeng** [cole-trapnell-lab/cicero#20]
Hello,

When I plotted the co-accessibility plot, the plot did not show any axis labels even if i included the argument `include_axis_track = T`

![image](https://github.com/cole-trapnell-lab/cicero/assets/60299660/4e539d4d-4620-4b3b-a049-ba894647721a)

Am I missing anything here? Thanks!!

Best,
Junxi

**Comment by hpliner** [comment]
Hi, Can you please include the code you're using to generate this plot and the sessionInfo for the R session where it was generated?

**Comment by hpliner** [comment]
Closing from lack of activity. Please reopen if still an issue
