### ISSUE TITLE
naive questions of using cicero

### ISSUE THREAD

**Issue by fzhangcode** [cole-trapnell-lab/cicero#4]
Hi, I just started using Cicero to analyze scATAC-seq data. I have 3 questions:

1. I noticed 'data(gene_annotation_sample)' only has annotations for Chr18, which ended up only 406 overlapped. So, where to get all the annotations?

2. I followed the steps in cicero to generate a gene x cell matrix, and performed tSNE on the generated gene x cell matrix. The tSNE looks not good - I am not sure if the reason is the matrix is only has ~400 features (genes)

3. Do you have a notebook of how to align the "tSNE clusters in the peaks x cells" to the "tSNE projection in the genes x cells"? Then that would be great to transfer the cell type labels to the peaks x cells clusters.

Thanks,
Fan

**Comment by ccruizm** [comment]
Hello! I have just started to analyse scATAC data and do have similar questions as @fzhangcode, specially the one on how to generate a gene annotation file of other chromosomes. Thanks in advance!

Cristian

**Comment by hpliner** [comment]
You will need to generate your own gene_annotation file, there's a bit of discussion on it here: https://groups.google.com/forum/#!topic/cicero-users/reWlCGW8Lcg and here https://groups.google.com/forum/#!topic/cicero-users/iZFiKZMzurU

For 2, I'm guessing that the tSNE will be much better when not using only 1 chromosome.

For 3, I'm not sure what exactly you're asking here, but given that the same cells are in each of those matrices, you should be able to transfer any annotations in a fairly straightforward way.

In future, please post questions to the cicero users group!

Best,
Hannah
