### ISSUE TITLE
apply cicero in bulk of ATAC-seq

### ISSUE THREAD

**Issue by deb0612** [cole-trapnell-lab/cicero#6]
Since cicero is used in scATAC-seq, is there any idea to apply cicero on a bulk of ATAC-seq?
I got more than 10 set of bulk ATAC-seq data,
Could I just simply aggregate those data sets to generate a cicero input matrix?

**Comment by hpliner** [comment]
Answered on the google group: https://groups.google.com/forum/#!topic/cicero-users/q43_aDaqeQk

**Comment by deb0612** [comment]
thanks for the reply,
I will go on trying to use cicero on bulk data.
Now I got 10 narrowpeak bed file. I tend to merge those peak files into an aggregated peak file, and count fragments separately to generate the count matrix.
Is there any suggusted toolkit to generate this aggregated peak file? I might try bedtool intersect first.
thanks
