### ISSUE TITLE
Question for trajector analysis

### ISSUE THREAD

**Issue by crushseven-7** [cole-trapnell-lab/cicero#7]
Hi,
Thank you for your wonderful software. Currently I am working on scATAC-seq data trajectory analysis. After I prepared input_cds and run estimate_size_factors() function, I got this error:
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function 'counts' for signature '"CellDataSet"'
How shall I modify the input cds to avoid this error?

Thank you,
Best,
Yan

**Comment by hpliner** [comment]
Duplicate of https://github.com/cole-trapnell-lab/cicero-release/issues/46
